FROM anonsolutions/indy-base

# Install indy python libraries and other dependencies
ADD requirements-docker-indy-community.txt .
RUN pip install --no-cache-dir -r requirements-docker-indy-community.txt

CMD ["bash"]
